mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  passwd: ""
  binlogCheckpointDir: "data"

meilisearch:
  host: "http://127.0.0.1:7700"
  apikey: ""

sync:
  - db: "test"
    table: "user"
    index: "user"
    primaryKey: "uuid"
    filterAbleField:
      - "name"
  - db: "test"
    table: "docs"
    index: "docs"
    primaryKey: "uuid"
    filterAbleField:
      - "name"