mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  passwd: ""
  binlogCheckpointDir: "data"

meilisearch:
  host: "http://search1.startops.com.cn:80"
  apikey: "zLj3v_WVnk-YxJcDucDMugHXotFv2fILHeyebkwj3o8"

sync:
  - db: "test"
    table: "user"
    index: "user"
    primaryKey: "uuid"
    filterAbleField:
      - "name"
  - db: "test"
    table: "docs"
    index: "docs"
    primaryKey: "uuid"
    filterAbleField:
      - "name"